CREATE DATABASE FOODDELIVERY;
USE FOODDELIVERY;
CREATE TABLE CUSTOMER
	(CUSTOMER_ID INT PRIMARY KEY,
	 PHONE_NUMBER VARCHAR(10) NOT NULL,
	 USERNAME VARCHAR(100) NOT NULL,
	 EMAIL_ID VARCHAR(100) UNIQUE,
	 ADDRESS VARCHAR(150) NOT NULL,
	 ORDERS_PLACED INT);
CREATE TABLE DELIVERY_PARTNER
	(PARTNER_ID INT PRIMARY KEY,
	 PHONE_NUMBER VARCHAR(10) NOT NULL,
	 DPNAME VARCHAR(100) NOT NULL,
	 ORDERS_DELIVERED INT);
CREATE TABLE ORDERS
	(ORDER_ID INT PRIMARY KEY,
	 PTIME DATETIME,
     CUSTOMER_ID INT,
     Restaurant_ID INT,
     PARTNER_ID INT,
     FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
     FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID),
     FOREIGN KEY (PARTNER_ID) REFERENCES DELIVERY_PARTNER(PARTNER_ID));
CREATE TABLE PAYMENT
	(PAYMENT_ID BIGINT PRIMARY KEY,
	 PAYMENT_TIME DATETIME,
	 AMT DOUBLE,
	 PTYPE VARCHAR(3) NOT NULL,
	 PSTATUS VARCHAR(1) NOT NULL,
     CUSTOMER_ID INT,
     FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID));  
CREATE TABLE RESTAURANT
	(Restaurant_ID INT PRIMARY KEY,
	Phone_Number VARCHAR(10) NOT NULL,
	RName VARCHAR(100) NOT NULL,
	Location VARCHAR(500) NOT NULL,
	Orders_Served INT);
CREATE TABLE MENU
	(Menu_ID INT PRIMARY KEY,
    MName VARCHAR(100) NOT NULL,
    Ingredients VARCHAR(500),
    Price DOUBLE NOT NULL,
    MStatus VARCHAR(5));
CREATE TABLE RATING
	(Remarks VARCHAR(500),
    Transaction_Number BIGINT PRIMARY KEY,
    Score VARCHAR(3),
    PDate DATE,
    Menu_ID INT,
    Restaurant_ID INT,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(RESTAURANT_ID),
    FOREIGN KEY (MENU_ID) REFERENCES RESTAURANT(MENU_ID));
CREATE TABLE SERVES
	(Menu_ID INT,
    Restaurant_ID INT,
    PRIMARY KEY (Restaurant_ID, Menu_ID),
    FOREIGN KEY (Restaurant_ID) REFERENCES RESTAURANT(Restaurant_ID),
    FOREIGN KEY (Menu_ID) REFERENCES MENU(Menu_ID));
show tables;
describe menu;
