USE FOODDELIVERY;
ALTER TABLE CUSTOMER 
MODIFY COLUMN USERNAME VARCHAR(100) CHECK (LENGTH(USERNAME)>=5),
MODIFY COLUMN ORDERS_PLACED INT DEFAULT 0;
ALTER TABLE DELIVERY_PARTNER
MODIFY COLUMN PHONE_NUMBER VARCHAR(10) UNIQUE,
MODIFY COLUMN DPNAME VARCHAR(100) CHECK (LENGTH(DPNAME)>=5),
MODIFY COLUMN ORDERS_DELIVERED INT DEFAULT 0;
ALTER TABLE PAYMENT
MODIFY COLUMN PAYMENT_TIME DATETIME NOT NULL,
MODIFY COLUMN AMT DOUBLE NOT NULL;
ALTER TABLE RESTAURANT
MODIFY COLUMN RNAME VARCHAR(100) CHECK (LENGTH(RNAME)>=5),
MODIFY OREDERS_SERVED INT DEFAULT 0;

SELECT USERNAME FROM CUSTOMER WHERE ADDRESS='DEHRADUN' AND ORDERS_PLACED=(SELECT MAX(ORDERS_PLACED)) LIMIT 1;
SELECT DPNAME FROM DELIVERY_PARTNER WHERE ORDERS_DELIVERED=(SELECT MAX(ORDERS_DELIVERED)) LIMIT 1;
SELECT RNAME FROM RESTAURANT WHERE LOCATION='DEHRADUN' AND OREDERS_SERVED>=20;
SELECT * FROM MENU WHERE MSTATUS='A' AND INGRIDIENTS='EGG' OR INGRIDIENTS='CHICKEN';
SELECT RNAME FROM RESTAURANT WHERE RESTAURANT_ID IN (SELECT RESTAURANT_ID FROM RATING WHERE SCORE='GOOD');
