CREATE DATABASE FOODDELIVERY;
USE FOODDELIVERY;
CREATE TABLE RESTAURANT
	(Restaurant_ID INT PRIMARY KEY,
	Phone_Number VARCHAR(10) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Location VARCHAR(500) NOT NULL,
	Orders_Served INT);
CREATE TABLE MENU
	(Menu_ID INT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Ingredients VARCHAR(500),
    Price DOUBLE NOT NULL,
    MStatus VARCHAR(5));
CREATE TABLE RATING
	(Remarks VARCHAR(500),
    Transaction_Number BIGINT PRIMARY KEY,
    Score VARCHAR(3),
    PDate DATE);
