CREATE VIEW C_VIEW AS 
(SELECT CUSTOMER_ID, PHONE_NUMBER,USERNAME,EMAIL_ID,ADDRESS,ORDERS_PLACED 
FROM CUSTOMER);

CREATE VIEW R_VIEW AS 
(SELECT RESTAURANT_ID, PHONE_NUMBER, RNAME, LOCATION, ORDERS_SERVED
FROM RESTAURANT);

CREATE VIEW D_VIEW AS 
(SELECT PARTNER_ID, PHONE_NUMBER, DPNAME, ORDERS_DELIVERED
FROM DELIVERY_PARTNER);

CREATE VIEW M_VIEW AS 
(SELECT MENU_ID, MNAME, INGREDIENTS, PRICE, MSTATUS
FROM MENU);
